# Generated by Django 3.1.3 on 2021-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(db_index=True, max_length=255, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True, verbose_name='接続元IPアドレス')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='me')),
                ('password', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('http_accept', models.CharField(max_length=1025, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
            ],
            options={
                'db_table': 'failed_login_attempt',
            },
        ),
    ]
